### ISSUE TITLE
error[E0658]: using the `?` macro Kleene operator for "at most one" repetition is unstable (see issue #48075)

### ISSUE THREAD

**Issue by bigtree9307** [Soveu/tinyvec_macros#2]
when I use diesel, I met this problem
![image](https://user-images.githubusercontent.com/17524799/129486574-57527969-997f-446f-a1bf-570cb2f82b19.png)

**Comment by Soveu** [comment]
@Lokathor :eyes:

**Comment by Soveu** [comment]
Weird, it was working on all previous rustc versions, hmm

**Comment by Soveu** [comment]
Wait, this syntax was stabilized 2 years ago @bigtree9307, what version of rustc are you using?

**Comment by Lokathor** [comment]
Yeah, tinyvec is supposed to work with 1.34 as the minimum, and it says [in the Rust release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1320-2019-01-17) that the `?` operator in macro definitions became stable in 1.32.

**Comment by bigtree9307** [comment]
@Soveu @Lokathor Thank you all guys, I found there was a rust-toolchain file in the root path of diesel specifying rust 1.31.0
